analyzer: 
  exclude: 
    - docs/**
    - generated/**
    - bricks/domain/__brick__/**
    - bricks/data/__brick__/**
    - bricks/presentation/__brick__/**
    - bricks/feature/__brick__/**
    - bricks/skeleton/__brick__/**